# -*- coding: utf-8 -*-
"""industry_pe_strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Qi_d-4-fIjE-ds6pj4Et0nV4w18ZBIa
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install finlab

from finlab import data
from finlab.backtest import sim
import pandas as pd
from finlab.optimize.combinations import ReportCollection

"""## 取得產業資訊"""

themes = data.get('security_industry_themes')
themes

"""## 簡單回測應用"""

from finlab import data
from finlab.backtest import sim

# 取出產業題材
themes = data.get('security_industry_themes')

# 選出產業包含「水泥」公司
ind = themes[themes['category'].str.contains('水泥')]
pe = data.get('price_earning_ratio:本益比')
ind_pe = pe[list(ind['stock_id'].dropna())]

# 計算每日產業本益比中位數
ind_pe_med = ind_pe.median(axis=1)

# 選出本益比小於同業本益比中位數且本益比小於25的公司
position = (ind_pe < ind_pe_med) & (ind_pe < 25)

# 回測
report = sim(position, upload=False)
report.display()

"""## 產業取樣"""

# 取出產業題材
themes = data.get('security_industry_themes')
# 複製一個 themes 來計算每個產業內有多少公司？
copied_themes = themes.copy()
# 將 category 陣列從文字格式轉成陣列格式
copied_themes['category'] = copied_themes['category'].apply(lambda s:eval(s))
# 以 pandas 的 explode 展開資料
exploded_themes = copied_themes.explode(['category'])
# 分群產業計算公司數
themes_count = exploded_themes.groupby('category')['stock_id'].count()
# 取出家數大於20家公司的主產業
large_themes = themes_count[themes_count >= 20].index
primary_themes = [i for i in large_themes if ':' not in i]

# primary_themes:
# ['LED照明產業', '交通運輸及航運', '人工智慧', '休閒娛樂', '其他',
#  '半導體', '印刷電路板', '大數據', '太空衛星科技', '太陽能產業',
#  '平面顯示器', '建材營造', '文化創意業', '汽車', '石化及塑橡膠',
#  '紡織', '能源元件', '被動元件', '製藥', '觸控面板',
#  '貿易百貨', '資通訊安全', '軟體服務', '通信網路', '連接器', '運動科技',
#  '醫療器材', '金融', '鋼鐵', '雲端運算', '電動車輛產業',
#  '電子商務', '電機機械', '電腦及週邊設備', '風力發電', '食品', '食品生技']

"""## 多產業回測分析"""

# 模擬回測至2018-12-31，用此回測結果選出前n大適合產業，再用選出的產業模擬
def sim_industry_position_by_pe(ind):
    stock_ids = exploded_themes[exploded_themes['category'].apply(lambda s:s==ind)]
    pe = data.get('price_earning_ratio:本益比')
    stock_ids = pe.columns.intersection(list(set(stock_ids['stock_id'])))
    ind_pe = pe[stock_ids]
    ind_pe_med = ind_pe.median(axis=1)
    position = (ind_pe < ind_pe_med)
    position = position.loc[:'2018']
    # 2週換股一次
    report = sim(position, upload=False, position_limit=0.2,resample='2W')
    return report


# 產生回測組合
reports = {ind: sim_industry_position_by_pe(ind) for ind in primary_themes }
# 放入回測報告組合比較器
collection = ReportCollection(reports)


# 繪圖產業回測報酬率曲線
import plotly.graph_objects as go
fig = go.Figure()
reports = collection.reports
# 報酬率曲線繪圖label按高低排序
dataset = {k: v for k, v in sorted(reports.items(), key=lambda item: item[1].creturn[-1], reverse=True)}
for k, v in dataset.items():
    series = v.creturn
    fig.add_trace(go.Scatter(x=series.index, y=series.values, mode='lines', name=k, meta=k,
                              hovertemplate="%{meta}<br>Date:%{x}<br>Creturns:%{y}<extra></extra>"))
fig.update_layout(title={'text': 'Cumulative returns', 'x': 0.49, 'y': 0.9, 'xanchor': 'center',
                          'yanchor': 'top'})
fig.show()


# 產生回測數據分群柱狀圖
collection.plot_stats().show()

# 產生評分熱力圖
heatmap = collection.plot_stats(mode='heatmap')
heatmap

print(list(dataset.keys())[:15])

"""## 產業回測"""

def get_industry_position_by_pe(ind):
    stock_ids = exploded_themes[exploded_themes['category'].apply(lambda s:s==ind)]
    pe = data.get('price_earning_ratio:本益比')
    stock_ids = pe.columns.intersection(list(set(stock_ids['stock_id'])))
    ind_pe = pe[stock_ids]
    ind_pe_med = ind_pe.median(axis=1)
    position = (ind_pe < ind_pe_med)
    return position


# 選出綜合評分前15高的產業
inds = heatmap.index[:15]
print(inds)

# 部位訊號合併
all_position = pd.concat([get_industry_position_by_pe(ind) for ind in inds],axis=1)

# 處理欄位重複問題，一家公司可能橫跨多產業，只要有一個產業選到，就選入。使用groupby mean處理重複的stock_id訊號判斷。
buy = all_position.groupby(level=0, axis=1).mean() > 0
report = sim(buy.loc['2019':], position_limit=0.2,resample='2W',upload=False)
report.benchmark = data.get('benchmark_return:發行量加權股價報酬指數').squeeze()
report.display()

"""## 同業本益比比較法～多產業投組

## 產業＊個股條件的回測結果
"""

def get_industry_position_by_pe(ind):
    stock_ids = exploded_themes[exploded_themes['category'].apply(lambda s:s==ind)]
    pe = data.get('price_earning_ratio:本益比')
    stock_ids = pe.columns.intersection(list(set(stock_ids['stock_id'])))
    ind_pe = pe[stock_ids]
    ind_pe_med = ind_pe.median(axis=1)
    position = (ind_pe < ind_pe_med)
    return position


inds = heatmap.index[:15]
print(heatmap.index[:15])
all_position = pd.concat([get_industry_position_by_pe(ind) for ind in inds],axis=1)
all_position= all_position.groupby(level=0, axis=1).mean() > 0

vol=data.get('price:成交股數')
close = data.get('price:收盤價')
pe = data.get('price_earning_ratio:本益比')
rev=data.get('monthly_revenue:當月營收')
rev_rf=data.get('monthly_revenue:去年同月增減(%)')
rev_ma3=rev.average(3)
rev_ma12=rev.average(12)
vol_ma5 = vol.average(5)

extra_conds = ((rev_ma3 > rev_ma12).sustain(3)) & (rev_rf >= 20) & (rev_ma3/rev_ma3.shift(12) >= 1.15) & (vol_ma5 >= 100*1000)
buy = all_position & extra_conds
buy *= vol_ma5
buy =buy[buy>0].is_smallest(10)


report = sim(buy, position_limit=0.2,resample='2W',stop_loss=0.2,upload=True)
report.benchmark = data.get('benchmark_return:發行量加權股價報酬指數').squeeze()
report.display()

"""## 個股條件回測"""

def get_industry_position_by_pe(ind):
    stock_ids = exploded_themes[exploded_themes['category'].apply(lambda s:s==ind)]
    pe = data.get('price_earning_ratio:本益比')
    stock_ids = pe.columns.intersection(list(set(stock_ids['stock_id'])))
    ind_pe = pe[stock_ids]
    ind_pe_med = ind_pe.median(axis=1)
    position = (ind_pe < ind_pe_med)
    return position


inds = heatmap.index[:15]
all_position = pd.concat([get_industry_position_by_pe(ind) for ind in inds],axis=1)
all_position= all_position.groupby(level=0, axis=1).mean() > 0

vol=data.get('price:成交股數')
close = data.get('price:收盤價')
pe = data.get('price_earning_ratio:本益比')
rev=data.get('monthly_revenue:當月營收')
rev_rf=data.get('monthly_revenue:去年同月增減(%)')
rev_ma3=rev.average(3)
rev_ma12=rev.average(12)
vol_ma5 = vol.average(5)

extra_conds = ((rev_ma3 > rev_ma12).sustain(3)) & (rev_rf >= 20) & (rev_ma3/rev_ma3.shift(12) >= 1.15) & (vol_ma5 >= 100*1000)
buy =  extra_conds
buy *= vol_ma5
buy =buy[buy>0].is_smallest(10)


report = sim(buy.reindex(pe.index), position_limit=0.2,resample='2W',stop_loss=0.2,upload=False)
report.benchmark = data.get('benchmark_return:發行量加權股價報酬指數').squeeze()
report.display()

