[project]
name = "ocr-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencc-python-reimplemented>=0.1.7",
    "opencv-python>=4.13.0.90",
    "paddleocr>=3.3.3",
    "paddlepaddle>=3.3.0",
    "pymupdf>=1.26.7",
    "fastapi",
    "uvicorn",
]
