-- topic_chain_edges: 供應鏈有向邊（人工策劃，靜態資料）
CREATE TABLE IF NOT EXISTS topic_chain_edges (
    source_topic_id TEXT NOT NULL,
    target_topic_id TEXT NOT NULL,
    PRIMARY KEY (source_topic_id, target_topic_id),
    CONSTRAINT fk_source FOREIGN KEY (source_topic_id)
        REFERENCES stock_topics (topic_id) ON DELETE CASCADE,
    CONSTRAINT fk_target FOREIGN KEY (target_topic_id)
        REFERENCES stock_topics (topic_id) ON DELETE CASCADE
);

-- RLS: 公開唯讀，供應鏈結構為共用參考資料
ALTER TABLE topic_chain_edges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read topic_chain_edges"
    ON topic_chain_edges FOR SELECT
    USING (true);

-- Index for efficient lookups
CREATE INDEX IF NOT EXISTS idx_chain_edges_source ON topic_chain_edges (source_topic_id);
CREATE INDEX IF NOT EXISTS idx_chain_edges_target ON topic_chain_edges (target_topic_id);

-- Seed: 初始供應鏈邊資料（對應 src/data/chain_edges.json）
-- 使用 ON CONFLICT DO NOTHING，允許重複執行
INSERT INTO topic_chain_edges (source_topic_id, target_topic_id) VALUES
    ('silicon-wafer', 'wafer-foundry'),
    ('semi-process-materials', 'wafer-foundry'),
    ('wafer-fab-equipment', 'wafer-foundry'),
    ('asic-ip-design', 'wafer-foundry'),
    ('hpc-network-ic', 'wafer-foundry'),
    ('edge-ai', 'wafer-foundry'),
    ('analog-power-ic', 'wafer-foundry'),
    ('ddic', 'wafer-foundry'),
    ('automotive-ic', 'wafer-foundry'),
    ('sic-gan-power', 'wafer-foundry'),
    ('wafer-foundry', 'cowos-advanced-packaging'),
    ('wafer-foundry', 'high-end-testing'),
    ('wafer-foundry', 'ic-substrate'),
    ('wafer-foundry', 'advanced-packaging-test'),
    ('wafer-foundry', 'advanced-packaging-process'),
    ('ic-substrate', 'cowos-advanced-packaging'),
    ('glass-core-substrate', 'ic-substrate'),
    ('fiberglass-cloth', 'glass-core-substrate'),
    ('packaging-materials', 'cowos-advanced-packaging'),
    ('advanced-packaging-automation', 'cowos-advanced-packaging'),
    ('cowos-advanced-packaging', 'ai-server-odm'),
    ('hbm', 'cowos-advanced-packaging'),
    ('hbm', 'ai-server-odm'),
    ('cxl-technology', 'ai-server-odm'),
    ('memory-modules', 'ai-server-odm'),
    ('niche-memory', 'memory-modules'),
    ('high-end-testing', 'ai-server-odm'),
    ('bbu', 'ai-server-odm'),
    ('psu', 'ai-server-odm'),
    ('thermal_components_air', 'ai-server-odm'),
    ('liquid_cooling_advanced', 'ai-server-odm'),
    ('ems-smt', 'ai-server-odm'),
    ('networking-equipment', 'ai-server-odm'),
    ('ai-server-odm', 'ai-server-chassis-rails'),
    ('pcb-manufacturing', 'ems-smt'),
    ('fpc', 'ems-smt'),
    ('connector', 'ems-smt'),
    ('mlcc-capacitor', 'ems-smt'),
    ('passive-inductor', 'ems-smt'),
    ('passive-resistor', 'ems-smt'),
    ('quartz-components', 'ems-smt'),
    ('precision-metal-casing', 'ai-server-chassis-rails'),
    ('silicon-photonics', 'networking-equipment'),
    ('high-speed-optics', 'networking-equipment'),
    ('hpc-network-ic', 'networking-equipment'),
    ('connector-highspeed', 'networking-equipment'),
    ('leo-satellite', 'networking-equipment'),
    ('silicon-photonics', 'high-speed-optics'),
    ('ic-distribution', 'ems-smt'),
    ('ic-distribution', 'ai-server-odm'),
    ('battery-materials', 'battery-cell-module'),
    ('battery-cell-module', 'ess-storage'),
    ('battery-cell-module', 'connector-automotive'),
    ('sic-gan-power', 'motor-drive-discrete'),
    ('sic-gan-power', 'ess-storage'),
    ('motor-drive-discrete', 'industrial-automation'),
    ('motor-drive-discrete', 'robotics_physical_ai'),
    ('industrial-automation', 'robotics_physical_ai'),
    ('connector-automotive', 'automotive-ic'),
    ('automotive-ic', 'motor-drive-discrete'),
    ('asic-ip-design', 'edge-ai'),
    ('edge-ai', 'robotics_physical_ai'),
    ('edge-ai', 'industrial-automation'),
    ('solar-energy', 'ess-storage'),
    ('offshore-wind', 'ess-storage'),
    ('electrical_equipment', 'ess-storage'),
    ('electrical_equipment', 'solar-energy'),
    ('electrical_equipment', 'offshore-wind'),
    ('water-environment', 'circular-economy-ewaste'),
    ('display-panel', 'ar-vr-xr-optics'),
    ('optical-lens-camera', 'ar-vr-xr-optics'),
    ('optical-sensors', 'ar-vr-xr-optics'),
    ('ar-vr-xr-optics', 'mobile'),
    ('pc-nb-tablet', 'cloud-msp'),
    ('mobile', 'e-commerce'),
    ('enterprise-saas', 'cloud-msp'),
    ('cybersecurity', 'cloud-msp'),
    ('it-si', 'cloud-msp'),
    ('cloud-msp', 'e-commerce'),
    ('ddic', 'display-panel'),
    ('optical-sensors', 'mobile'),
    ('optical-lens-camera', 'mobile'),
    ('hpc-network-ic', 'leo-satellite'),
    ('asic-ip-design', 'leo-satellite'),
    ('cnc-machine-tool', 'wafer-fab-equipment'),
    ('cnc-machine-tool', 'precision-metal-casing'),
    ('cnc-machine-tool', 'advanced-packaging-automation'),
    ('pcb-manufacturing', 'networking-equipment'),
    ('fpc', 'mobile'),
    ('fpc', 'pc-nb-tablet'),
    ('connector', 'ai-server-chassis-rails'),
    ('psu', 'ems-smt'),
    ('thermal_components_air', 'ems-smt'),
    ('liquid_cooling_advanced', 'ai-server-chassis-rails'),
    ('mlcc-capacitor', 'automotive-ic'),
    ('passive-inductor', 'automotive-ic'),
    ('battery-cell-module', 'pc-nb-tablet'),
    ('wafer-foundry', 'niche-memory'),
    ('wafer-foundry', 'hbm'),
    ('packaging-materials', 'ic-substrate'),
    ('semi-process-materials', 'cowos-advanced-packaging'),
    ('silicon-photonics', 'leo-satellite'),
    ('industrial-automation', 'cnc-machine-tool')
ON CONFLICT (source_topic_id, target_topic_id) DO NOTHING;
